name: pref
description: Create Preference Screens easily with advanced features and sub-pages
homepage: https://github.com/DavBfr/flutter_pref/tree/master/pref
repository: https://github.com/DavBfr/flutter_pref
issue_tracker: https://github.com/DavBfr/flutter_pref/issues
author: David PHAM-VAN <dev.nfet.net@gmail.com>
version: 2.0.1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
