name: pref
description: Create Preference Screens easily with advanced features and sub-pages
homepage: https://github.com/DavBfr/flutter_pref/tree/master/pref
repository: https://github.com/DavBfr/flutter_pref
issue_tracker: https://github.com/DavBfr/flutter_pref/issues
screenshots:
  - description: 'Example pref panel for a mobile phone'
    path: example.jpg
version: 2.7.1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.1.1
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
