name: example
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker:
  logging:
  number_selector:
  pref:

dependency_overrides:
  pref:
    path: ..


dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
